import { StyleSheet } from 'react-native';

const estilos = StyleSheet.create({
  Tela_Carnaval_fundo: {
    flex: 1,
    backgroundColor: 'darkred',
    padding: 10,
    borderRadius: 25,
    margin: 10,
  },
  Tela_Carnaval_Cab: {
    backgroundColor: '#fff',
    alignItems: 'center',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    paddingTop: 20,
    paddingBottom: 10,
    flexDirection: 'row',
    gap: 10,
  },
  Tela_Carnaval_Img: {
    width: 80,
    height: 80,
    marginRight: 10,
    borderRadius: 10,
  },
  Tela_Carnaval_Cab_Textos: {
    flex: 1,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  Tela_Carnaval_Titulo: {
    fontSize: 28,
    fontWeight: 'bold',
    color: 'darkred',
    marginBottom: 0,
  },
  Tela_Carnaval_SubTitulo: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#222',
    marginBottom: 0,
  },
  Tela_Carnaval_Corpo: {
    backgroundColor: '#fff',
    borderRadius: 0,
    padding: 20,
    flex: 1,
  },
  Tela_Carnaval_Intro: {
    fontSize: 16,
    color: 'darkred',
    fontWeight: 'bold',
    marginTop: 10,
    marginBottom: 5,
  },
  Tela_Carnaval_IntroTexto: {
    fontSize: 15,
    color: '#222',
    marginBottom: 10,
    textAlign: 'justify',
  },
  Tela_Carnaval_Destaque: {
    fontSize: 16,
    color: 'darkred',
    fontWeight: 'bold',
    marginVertical: 10,
    textAlign: 'justify',
  },
  Tela_Carnaval_Origens: {
    fontSize: 16,
    color: 'darkred',
    fontWeight: 'bold',
    marginTop: 10,
    marginBottom: 5,
  },
  Tela_Carnaval_OrigensTexto: {
    fontSize: 15,
    color: '#222',
    marginBottom: 10,
    textAlign: 'justify',
  },
  Tela_Carnaval_Curiosidade: {
    fontSize: 16,
    color: 'darkred',
    fontWeight: 'bold',
    marginTop: 10,
    marginBottom: 5,
  },
  Tela_Carnaval_ImgCuriosidade: {
    width: 100,
    height: 70,
    borderRadius: 8,
    marginBottom: 5,
  },
  Tela_Carnaval_CuriosidadeTexto: {
    fontSize: 15,
    color: '#222',
    marginBottom: 10,
    textAlign: 'justify',
  },
  Tela_Carnaval_Rodape: {
    backgroundColor: '#fff',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    borderTopWidth: 2,
    borderTopColor: 'darkred',
    marginTop: 'auto',
  },
  Tela_Principal_fundo: {
    flex: 1,
    backgroundColor: '#ededed',
    padding: 10,
    borderRadius: 25,
    margin: 10,
  },
  Tela_Principal_Cab: {
    backgroundColor: '#fff',
    alignItems: 'center',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    paddingTop: 20,
    paddingBottom: 10,
  },
  Tela_Principal_Titulo: {
    fontSize: 32,
    fontWeight: 'bold',
    marginBottom: 0,
    textAlign: 'center',
  },
  Tela_Principal_SubTitulo1: {
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: 20,
    marginBottom: 10,
    textAlign: 'center',
  },
  Tela_Principal_SubTitulo2: {
    fontSize: 16,
    color: '#444',
    marginBottom: 10,
    textAlign: 'center',
  },
  Tela_Principal_Corpo: {
    backgroundColor: '#fff',
    alignItems: 'center',
    paddingVertical: 20,
  },
  Tela_Principal_Botoes: {
    borderWidth: 2,
    borderColor: '#a00',
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 30,
    marginVertical: 8,
    alignItems: 'center',
    minWidth: 180,
  },
  Tela_Principal_Rodape: {
    backgroundColor: '#fff',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    borderTopWidth: 2,
    borderTopColor: '#ededed',
    marginTop: 'auto',
  },
});

export { estilos };
